apiVersion: v1
kind: Service
metadata:
  name: react-kube-service
spec:
  type: NodePort
  selector:
    app: react-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30036  # You can set this manually or let Kubernetes assign (range 30000-32767)
